var data = {
  "city": {
    "id": 92602,
    "city": "Irvine",
    "lat": 33.74,
    "lon": -117.75,
    "state": "CA",
    "country": "us",
    "zip": "92602",
    "member_count": 13650
  },
  "events": [
    {
      "created": 1566077209000,
      "duration": 7200000,
      "id": "dsjtgrybcmbjc",
      "name": "Code Market - Buy & Sell Software Code",
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1601139600000,
      "local_date": "2020-09-26",
      "local_time": "10:00",
      "updated": 1566077209000,
      "utc_offset": -25200000,
      "waitlist_count": 0,
      "yes_rsvp_count": 1,
      "venue": {
        "id": 26080792,
        "name": "WeWork Coworking & Office Space",
        "lat": 33.65270233154297,
        "lon": -117.74777221679688,
        "repinned": false,
        "address_1": "200 Spectrum Center Dr STE 300",
        "city": "Irvine",
        "country": "us",
        "localized_country_name": "USA",
        "zip": "92618",
        "state": "CA"
      },
      "is_online_event": false,
      "group": {
        "created": 1458608603000,
        "name": "Code Market - Orange County",
        "id": 19741661,
        "join_mode": "open",
        "lat": 33.709999084472656,
        "lon": -117.70999908447266,
        "urlname": "codemarket-oc2",
        "who": "Code Lovers",
        "localized_location": "Irvine, CA",
        "state": "CA",
        "country": "us",
        "region": "en_US",
        "timezone": "US/Pacific"
      },
      "link": "https://www.meetup.com/codemarket-oc2/events/dsjtgrybcmbjc/",
      "description": "<p>This meetup is for Software Developers/Programmers/Coders/Data Scientists/ML/AI professionals.</p>",
        "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1584557507000,
      "duration": 3600000,
      "id": "tvmvqrybcmbmc",
      "name": "Want to Learn To Code but can't quit your day job?",
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1601431200000,
      "local_date": "2020-09-29",
      "local_time": "19:00",
      "updated": 1584557507000,
      "utc_offset": -25200000,
      "waitlist_count": 0,
      "yes_rsvp_count": 1,
      "venue": {
        "id": 25596528,
        "name": "LearningFuze Web Development",
        "lat": 33.634857177734375,
        "lon": -117.74046325683594,
        "repinned": true,
        "address_1": "9200 Irvine Center Drive 2nd Floor ",
        "city": "Irvine",
        "country": "us",
        "localized_country_name": "USA",
        "zip": "",
        "state": "CA"
      },
      "is_online_event": false,
      "group": {
        "created": 1407851519000,
        "name": "OC Women Web Developers",
        "id": 16342292,
        "join_mode": "open",
        "lat": 33.7400016784668,
        "lon": -117.75,
        "urlname": "OC-New-Women-Can-Code",
        "who": "Members",
        "localized_location": "Irvine, CA",
        "state": "CA",
        "country": "us",
        "region": "en_US",
        "timezone": "US/Pacific"
      },
      "link": "https://www.meetup.com/OC-New-Women-Can-Code/events/tvmvqrybcmbmc/",
      "description": "<p>Are you interested in Learning To Code and can't quit your day job? We have the perfect solution. Our flexible part-time course was developed with you in mind. Join us to get all of your questions answered. We are here to help!</p>",
        "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1570621097000,
      "duration": 7200000,
      "id": "nwfxjrybcnbbc",
      "name": "Deep Learning & Statistics For Algotrading",
      "rsvp_limit": 35,
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1603245600000,
      "local_date": "2020-10-20",
      "local_time": "19:00",
      "updated": 1570621097000,
      "utc_offset": -25200000,
      "waitlist_count": 0,
      "yes_rsvp_count": 5,
      "venue": {
        "id": 26175449,
        "name": "2640 Main St",
        "lat": 33.68111038208008,
        "lon": -117.84185791015625,
        "repinned": true,
        "address_1": "2640 Main St",
        "city": "Irvine",
        "country": "us",
        "localized_country_name": "USA",
        "zip": "92614",
        "state": "CA"
      },
      "is_online_event": false,
      "group": {
        "created": 1548298868000,
        "name": "Irvine Algotrading",
        "id": 30998066,
        "join_mode": "open",
        "lat": 33.68000030517578,
        "lon": -117.83000183105469,
        "urlname": "Irvine-Algotrading",
        "who": "Members",
        "localized_location": "Irvine, CA",
        "state": "CA",
        "country": "us",
        "region": "en_US",
        "timezone": "US/Pacific"
      },
      "link": "https://www.meetup.com/Irvine-Algotrading/events/nwfxjrybcnbbc/",
      "description": "<p>Are you interested in deep learning and want to see how it can be applied to trading? Look no further, this is the meetup for you!</p> <p>We'll be going through a wealth of code and technical approaches that can be applied to algorithmic trading strategies. Areas of interest for these discussions: reinforcement learning, deep Q learning, statistical analyses, regressions, and more.</p> <p>You do NOT need ANY programming experience to join us! One major point of the group is to pair up finance professionals and talented programmers to mutually learn from each other. Hopefully, the meetings can spark some collaboration on successful implementations of algotrading!</p> <p>Yes, there will be jupyter notebooks and snippets of code offered to group as interesting things are developed. We will coordinate the file sharing and information links over slack, so please join our channel with the link above!</p> <p>This event is the complement to our other biweekly event, placing a focus on the programming and machine learning techniques rather than actual trading strategies. I highly suggest attending both events to get a well rounded base of knowledge, and to meet experts in both finance and machine learning!</p> ",
      "how_to_find_us": "Park anywhere in the front, side, or back of the building and walk to the front to get checked in/badged in.  We are guests of a very gracious datacenter who believes in what we're doing",
      "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1600702660000,
      "duration": 7200000,
      "id": "273409740",
      "name": "MasterMinds Startup Accelerator Workshop #44 - Going Public Q&A with TSX",
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1602115200000,
      "local_date": "2020-10-07",
      "local_time": "17:00",
      "updated": 1600702719000,
      "utc_offset": -25200000,
      "waitlist_count": 0,
      "yes_rsvp_count": 11,
      "venue": {
        "id": 26906060,
        "name": "Online event",
        "repinned": false,
        "country": "",
        "localized_country_name": ""
      },
      "is_online_event": true,
      "group": {
        "created": 1444685797000,
        "name": "Digital Marketing, SEO, PPC, e-Commerce Meetup",
        "id": 19021340,
        "join_mode": "open",
        "lat": 33.68000030517578,
        "lon": -117.62999725341797,
        "urlname": "Orange-County-Digital-Marketing-SEO-e-Commerce-Meetup",
        "who": "Startup Founders",
        "localized_location": "Foothill Ranch, CA",
        "state": "CA",
        "country": "us",
        "region": "en_US",
        "timezone": "US/Pacific"
      },
      "link": "https://www.meetup.com/Orange-County-Digital-Marketing-SEO-e-Commerce-Meetup/events/273409740/",
      "description": "<p>ENTREPRENEURS: Bring your startup strategy questions and pitches to MasterMinds Startup Accelerator Q&amp;A Workshop #44 for fun info and networking!</p>",
        "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1600367645000,
      "duration": 7200000,
      "id": "273325175",
      "name": "GROUP CLOSING Moving Invitation:  Free Event Ticket for you!",
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1601413200000,
      "local_date": "2020-09-29",
      "local_time": "14:00",
      "updated": 1600998522000,
      "utc_offset": -25200000,
      "waitlist_count": 0,
      "yes_rsvp_count": 1,
      "venue": {
        "id": 26906060,
        "name": "Online event",
        "repinned": false,
        "country": "",
        "localized_country_name": ""
      },
      "is_online_event": true,
      "group": {
        "created": 1444685797000,
        "name": "Digital Marketing, SEO, PPC, e-Commerce Meetup",
        "id": 19021340,
        "join_mode": "open",
        "lat": 33.68000030517578,
        "lon": -117.62999725341797,
        "urlname": "Orange-County-Digital-Marketing-SEO-e-Commerce-Meetup",
        "who": "Startup Founders",
        "localized_location": "Foothill Ranch, CA",
        "state": "CA",
        "country": "us",
        "region": "en_US",
        "timezone": "US/Pacific"
      },
      "link": "https://www.meetup.com/Orange-County-Digital-Marketing-SEO-e-Commerce-Meetup/events/273325175/",
      "description": "<p>Hi – we’re CLOSING this group but you'll get a FREE TICKET if you come with us!</p>",
        "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1600800068000,
      "duration": 7200000,
      "id": "273435241",
      "name": "GROUP CLOSING Moving Invitation:  Free Event Ticket for you!",
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1601431200000,
      "local_date": "2020-09-29",
      "local_time": "19:00",
      "updated": 1600998387000,
      "utc_offset": -25200000,
      "waitlist_count": 0,
      "yes_rsvp_count": 1,
      "venue": {
        "id": 26906060,
        "name": "Online event",
        "repinned": false,
        "country": "",
        "localized_country_name": ""
      },
      "is_online_event": true,
      "group": {
        "created": 1506368426000,
        "name": "Startup Incubator",
        "id": 26050756,
        "join_mode": "open",
        "lat": 33.7400016784668,
        "lon": -117.75,
        "urlname": "Startup-Incubator-Master-Mind-Group",
        "who": "Accelerators",
        "localized_location": "Irvine, CA",
        "state": "CA",
        "country": "us",
        "region": "en_US",
        "timezone": "US/Pacific"
      },
      "link": "https://www.meetup.com/Startup-Incubator-Master-Mind-Group/events/273435241/",
      "description": "<p>Hi – we’re CLOSING this group but you'll get a FREE TICKET if you come with us!</p>",
        "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1599111275000,
      "duration": 10800000,
      "id": "273000536",
      "name": "Regression Models with R Applications **Sign-up on Eventbrite**",
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1602637200000,
      "local_date": "2020-10-13",
      "local_time": "18:00",
      "updated": 1599111290000,
      "utc_offset": -25200000,
      "waitlist_count": 0,
      "yes_rsvp_count": 1,
      "venue": {
        "id": 26906060,
        "name": "Online event",
        "repinned": false,
        "country": "",
        "localized_country_name": ""
      },
      "is_online_event": true,
      "group": {
        "created": 1418800807000,
        "name": "Orange County R Users Group (OCRUG)",
        "id": 18258391,
        "join_mode": "open",
        "lat": 33.650001525878906,
        "lon": -117.81999969482422,
        "urlname": "OC-RUG",
        "who": "Members",
        "localized_location": "Irvine, CA",
        "state": "CA",
        "country": "us",
        "region": "en_US",
        "timezone": "US/Pacific"
      },
      "link": "https://www.meetup.com/OC-RUG/events/273000536/",
      "description": "<p>***********************************************************************<br/>*** Register for this event on Eventbrite ***</p>",
        "visibility": "public",
      "pro_is_email_shared": false,
      "member_pay_fee": false
    },
    {
      "created": 1599766245000,
      "duration": 7200000,
      "fee": {
        "accepts": "cash",
        "amount": 25,
        "currency": "USD",
        "description": "",
        "label": "Price",
        "required": false
      },
      "id": "zjjmxrybcnbjb",
      "name": "Manifesting From Your Soul Code",
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1602036000000,
      "local_date": "2020-10-06",
      "local_time": "19:00",
      "updated": 1600706257000,
      "utc_offset": -25200000,
      "waitlist_count": 0,
      "yes_rsvp_count": 2,
      "venue": {
        "id": 26906060,
        "name": "Online event",
        "repinned": false,
        "country": "",
        "localized_country_name": ""
      },
      "is_online_event": true,
      "group": {
        "created": 1279222664000,
        "name": "Personal Growth Community - HeartSpace",
        "id": 1676005,
        "join_mode": "open",
        "lat": 33.68000030517578,
        "lon": -117.83000183105469,
        "urlname": "smhasoc",
        "who": "Seekers",
        "localized_location": "Irvine, CA",
        "state": "CA",
        "country": "us",
        "region": "en_US",
        "timezone": "US/Pacific"
      },
      "link": "https://www.meetup.com/smhasoc/events/zjjmxrybcnbjb/",
      "description": "<p>with Roz Esposito</p> <p>As you unplug from your daily routines, there is an opening and an opportunity to recognize what’s truly meaningful in your life. What no longer fits? What wants to emerge? Join us for a deep dive into accessing your Soul Code – that which is indelibly etched upon your soul – your true calling in this life. From this place you unleash the tremendous power to manifest without resistance.</p> <p>7 PM – 9 PM<br/>Cost: $25</p>",
        "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1599766245000,
      "duration": 7200000,
      "fee": {
        "accepts": "cash",
        "amount": 25,
        "currency": "USD",
        "description": "",
        "label": "Price",
        "required": false
      },
      "id": "zjjmxrybcmbmc",
      "name": "Manifesting From Your Soul Code",
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1601431200000,
      "local_date": "2020-09-29",
      "local_time": "19:00",
      "updated": 1600975906000,
      "utc_offset": -25200000,
      "waitlist_count": 0,
      "yes_rsvp_count": 3,
      "venue": {
        "id": 26906060,
        "name": "Online event",
        "repinned": false,
        "country": "",
        "localized_country_name": ""
      },
      "is_online_event": true,
      "group": {
        "created": 1279222664000,
        "name": "Personal Growth Community - HeartSpace",
        "id": 1676005,
        "join_mode": "open",
        "lat": 33.68000030517578,
        "lon": -117.83000183105469,
        "urlname": "smhasoc",
        "who": "Seekers",
        "localized_location": "Irvine, CA",
        "state": "CA",
        "country": "us",
        "region": "en_US",
        "timezone": "US/Pacific"
      },
      "link": "https://www.meetup.com/smhasoc/events/zjjmxrybcmbmc/",
      "description": "<p>with Roz Esposito</p> <p>As you unplug from your daily routines, there is an opening and an opportunity to recognize what’s truly meaningful in your life. What no longer fits? What wants to emerge? Join us for a deep dive into accessing your Soul Code – that which is indelibly etched upon your soul – your true calling in this life. From this place you unleash the tremendous power to manifest without resistance.</p> <p>7 PM – 9 PM<br/>Cost: $25</p>",
        "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1600448911000,
      "duration": 7200000,
      "id": "273347786",
      "name": "GROUP CLOSING Moving Invitation:  Free Event Ticket for you!",
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1601463600000,
      "local_date": "2020-09-30",
      "local_time": "04:00",
      "updated": 1600998466000,
      "utc_offset": -25200000,
      "waitlist_count": 0,
      "yes_rsvp_count": 3,
      "venue": {
        "id": 26906060,
        "name": "Online event",
        "repinned": false,
        "country": "",
        "localized_country_name": ""
      },
      "is_online_event": true,
      "group": {
        "created": 1452583254000,
        "name": "VC & Angel Investments",
        "id": 19325553,
        "join_mode": "open",
        "lat": 33.650001525878906,
        "lon": -117.81999969482422,
        "urlname": "startup-fin",
        "who": "Startup Hustlers",
        "localized_location": "Irvine, CA",
        "state": "CA",
        "country": "us",
        "region": "en_US",
        "timezone": "US/Pacific"
      },
      "link": "https://www.meetup.com/startup-fin/events/273347786/",
      "description": "<p>Hi – we’re CLOSING this group but you'll get a FREE TICKET if you come with us!</p>",
        "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1566793772000,
      "duration": 7200000,
      "id": "xplfhrybcnbjb",
      "name": "Automated Trading Strategy Workshop",
      "rsvp_limit": 25,
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1602036000000,
      "local_date": "2020-10-06",
      "local_time": "19:00",
      "updated": 1566793772000,
      "utc_offset": -25200000,
      "waitlist_count": 0,
      "yes_rsvp_count": 7,
      "venue": {
        "id": 26175449,
        "name": "2640 Main St",
        "lat": 33.68111038208008,
        "lon": -117.84185791015625,
        "repinned": true,
        "address_1": "2640 Main St",
        "city": "Irvine",
        "country": "us",
        "localized_country_name": "USA",
        "zip": "92614",
        "state": "CA"
      },
      "is_online_event": false,
      "group": {
        "created": 1548298868000,
        "name": "Irvine Algotrading",
        "id": 30998066,
        "join_mode": "open",
        "lat": 33.68000030517578,
        "lon": -117.83000183105469,
        "urlname": "Irvine-Algotrading",
        "who": "Members",
        "localized_location": "Irvine, CA",
        "state": "CA",
        "country": "us",
        "region": "en_US",
        "timezone": "US/Pacific"
      },
      "link": "https://www.meetup.com/Irvine-Algotrading/events/xplfhrybcnbjb/",
      "description": "<p>Join us for a thought-provoking evening as we demonstrate and discuss various strategies for automated trading algorithms!</p> <p>This meetup is a workshop where we'll not only talking about trading, but we'll do full on backtesting and optimization of a strategy live as we hold an open discussion. We definitely suggest bringing your laptop to try out strategies along with us, but no laptops are required. There's a flatscreen in the room projecting my computer screen so everyone can see how the strategies are setup and backtested via ninjatrader or other means.</p> <p>Of the biweekly meetings, this meetup is centered on the financial and statistical side of algotrading, avoiding deep dives into the technical aspects of what we're doing. If you want to learn more about trading, or your expertise is centered in finance and you want to get into algotrading, this is the meetup for you!</p> <p>Waters will be provided, the WiFi is pretty good, and parking is a breeze.</p> ",
      "how_to_find_us": "Free parking in the parking lot surrounding the building, all the way around!  The building is brown and has no logos, it is next to a new apartment building under construction.",
      "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1590695533000,
      "duration": 5400000,
      "id": "skmrsrybcnbcb",
      "name": "Let's Meetup, Network and Refer Business To Each Other!",
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1601578800000,
      "local_date": "2020-10-01",
      "local_time": "12:00",
      "updated": 1590695533000,
      "utc_offset": -25200000,
      "waitlist_count": 0,
      "yes_rsvp_count": 3,
      "venue": {
        "id": 26906060,
        "name": "Online event",
        "repinned": true,
        "country": "",
        "localized_country_name": ""
      },
      "is_online_event": true,
      "group": {
        "created": 1459281643000,
        "name": "OC United BNI - Business Networking - Irvine, CA",
        "id": 19774146,
        "join_mode": "approval",
        "lat": 33.7400016784668,
        "lon": -117.75,
        "urlname": "OC-United-BNI-Business-Networking-Irvine-CA",
        "who": "Members",
        "localized_location": "Irvine, CA",
        "state": "CA",
        "country": "us",
        "region": "en_US",
        "timezone": "US/Pacific"
      },
      "link": "https://www.meetup.com/OC-United-BNI-Business-Networking-Irvine-CA/events/skmrsrybcnbcb/",
      "description": "<p>*** Virtual Meeting***<br/>**Please email Katelynn at [masked] or Cynthia [masked] for the Zoom code**</p> <p>Are you looking to grow your business Network?</p> <p>Do you understand the value of referrals from fellow business professionals?</p> <p>Come visit our meeting and witness the power of referral marketing!</p> <p>This is our weekly meeting where we will be discussing opportunities to refer business to each other and help grow each others' businesses. Don't miss this opportunity to network with a group of highly successful referral-minded business professionals.</p> <p>Our year to date is $1,696,792. That means $1,696,792 of business revenue has been generated from referrals!</p> <p>Last week alone we had 20 referrals given!</p> <p>We are in search of professionals to become qualified members of our group in order to share referrals and grow your business.</p> <p>Only one individual per profession is allowed to be a member, so you get to lock out your competition.</p> <p>Please bring plenty of business cards and your biggest networking smile. Fee for all members and guests is $20 and includes lunch.</p>",
      "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1590695533000,
      "duration": 5400000,
      "id": "skmrsrybcnblb",
      "name": "Let's Meetup, Network and Refer Business To Each Other!",
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1602183600000,
      "local_date": "2020-10-08",
      "local_time": "12:00",
      "updated": 1590695533000,
      "utc_offset": -25200000,
      "waitlist_count": 0,
      "yes_rsvp_count": 3,
      "venue": {
        "id": 26906060,
        "name": "Online event",
        "repinned": true,
        "country": "",
        "localized_country_name": ""
      },
      "is_online_event": true,
      "group": {
        "created": 1459281643000,
        "name": "OC United BNI - Business Networking - Irvine, CA",
        "id": 19774146,
        "join_mode": "approval",
        "lat": 33.7400016784668,
        "lon": -117.75,
        "urlname": "OC-United-BNI-Business-Networking-Irvine-CA",
        "who": "Members",
        "localized_location": "Irvine, CA",
        "state": "CA",
        "country": "us",
        "region": "en_US",
        "timezone": "US/Pacific"
      },
      "link": "https://www.meetup.com/OC-United-BNI-Business-Networking-Irvine-CA/events/skmrsrybcnblb/",
      "description": "<p>*** Virtual Meeting***<br/>**Please email Katelynn at [masked] or Cynthia [masked] for the Zoom code**</p> <p>Are you looking to grow your business Network?</p> <p>Do you understand the value of referrals from fellow business professionals?</p> <p>Come visit our meeting and witness the power of referral marketing!</p> <p>This is our weekly meeting where we will be discussing opportunities to refer business to each other and help grow each others' businesses. Don't miss this opportunity to network with a group of highly successful referral-minded business professionals.</p> <p>Our year to date is $1,696,792. That means $1,696,792 of business revenue has been generated from referrals!</p> <p>Last week alone we had 20 referrals given!</p> <p>We are in search of professionals to become qualified members of our group in order to share referrals and grow your business.</p> <p>Only one individual per profession is allowed to be a member, so you get to lock out your competition.</p> <p>Please bring plenty of business cards and your biggest networking smile. Fee for all members and guests is $20 and includes lunch.</p>",
      "visibility": "public",
      "member_pay_fee": false
    },
    {
      "created": 1550338323000,
      "duration": 7200000,
      "id": "ffnwrqybcmbjc",
      "name": "Fun & easy way to play more tennis (read event description)",
      "date_in_series_pattern": false,
      "status": "upcoming",
      "time": 1601172000000,
      "local_date": "2020-09-26",
      "local_time": "19:00",
      "updated": 1550338323000,
      "utc_offset": -25200000,
      "waitlist_count": 0,
      "yes_rsvp_count": 1,
      "is_online_event": false,
      "group": {
        "created": 1525928530000,
        "name": "PlayYourCourt Irvine Tennis",
        "id": 28442410,
        "join_mode": "open",
        "lat": 33.7400016784668,
        "lon": -117.75,
        "urlname": "PlayYourCourt-Irvine-Tennis",
        "who": "Members",
        "localized_location": "Irvine, CA",
        "state": "CA",
        "country": "us",
        "region": "en_US",
        "timezone": "US/Pacific"
      },
      "link": "https://www.meetup.com/PlayYourCourt-Irvine-Tennis/events/ffnwrqybcmbjc/",
      "description": "<p>We’re still working to get more people into these Meetups, but our goal is to give PlayYourCourt members a few social tennis outings each week in addition to your practice sessions and Challenge League matches.</p> <p>These Meetups are co-ed, super laid back, and all skill levels are welcome. Post your skill level and a suggested court in the comments section so we can round up as many players as we can for some tennis fun!</p> <p>Also, if you’re looking to meet new practice partners or play some matches and you aren’t already in the PlayYourCourt Community, you can go here to see what we’re all about and sign up:</p>",
        "visibility": "public",
      "member_pay_fee": false
    }
  ]
}

// var wellness = {
//   "city": {
//     "id": 92602,
//     "city": "Irvine",
//     "lat": 33.74,
//     "lon": -117.75,
//     "state": "CA",
//     "country": "us",
//     "zip": "92602",
//     "member_count": 13650
//   },
//   "events": [
//     {
//       "created": 1598287398000,
//       "duration": 3600000,
//       "id": "chvtwrybcmbjc",
//       "name": "💻 How to deal with all this stress? Webinar. Time: TBA",
//       "date_in_series_pattern": false,
//       "status": "upcoming",
//       "time": 1601146800000,
//       "local_date": "2020-09-26",
//       "local_time": "12:00",
//       "updated": 1598287398000,
//       "utc_offset": -25200000,
//       "waitlist_count": 0,
//       "yes_rsvp_count": 1,
//       "is_online_event": false,
//       "group": {
//         "created": 1413136535000,
//         "name": "OC Wellness Meetup",
//         "id": 17572152,
//         "join_mode": "open",
//         "lat": 33.689998626708984,
//         "lon": -117.79000091552734,
//         "urlname": "OC-Wellness-Meetup",
//         "who": "Wellness enthusiasts",
//         "localized_location": "Irvine, CA",
//         "state": "CA",
//         "country": "us",
//         "region": "en_US",
//         "timezone": "US/Pacific"
//       },
//       "link": "https://www.meetup.com/OC-Wellness-Meetup/events/chvtwrybcmbjc/",
//       "description": "<p>What to do in this time of uncertainty and high stress?<br/>We will conduct a series of webinars to address worries and anxieties of our community. Time is to be announced. For details about the webinar, please RSVP at [masked]</p> <p>Please watch this video message of hope to all members of our meetup:",
//         "visibility": "public",
//       "member_pay_fee": false
//     },
//     {
//       "created": 1598339934000,
//       "duration": 3600000,
//       "fee": {
//         "accepts": "cash",
//         "amount": 20,
//         "currency": "USD",
//         "description": "",
//         "label": "Price",
//         "required": false
//       },
//       "id": "lwhvwrybcmbmc",
//       "name": "Restorative Yoga & Meditation - English & Spanish",
//       "date_in_series_pattern": false,
//       "status": "upcoming",
//       "time": 1601431200000,
//       "local_date": "2020-09-29",
//       "local_time": "19:00",
//       "updated": 1600976094000,
//       "utc_offset": -25200000,
//       "waitlist_count": 0,
//       "yes_rsvp_count": 2,
//       "venue": {
//         "id": 26916173,
//         "name": "HeartSpace Online",
//         "lat": 33.68795394897461,
//         "lon": -117.86682891845703,
//         "repinned": true,
//         "address_1": "18271 McDurmott W   ",
//         "address_2": "Suite G",
//         "city": "Irvine",
//         "country": "us",
//         "localized_country_name": "USA",
//         "zip": "92614",
//         "state": "ca"
//       },
//       "is_online_event": false,
//       "group": {
//         "created": 1279222664000,
//         "name": "Personal Growth Community - HeartSpace",
//         "id": 1676005,
//         "join_mode": "open",
//         "lat": 33.68000030517578,
//         "lon": -117.83000183105469,
//         "urlname": "smhasoc",
//         "who": "Seekers",
//         "localized_location": "Irvine, CA",
//         "state": "CA",
//         "country": "us",
//         "region": "en_US",
//         "timezone": "US/Pacific"
//       },
//       "link": "https://www.meetup.com/smhasoc/events/lwhvwrybcmbmc/",
//       "description": "<p>This class is designed to access the transformative power of forgiveness. Through a series of yoga techniques including postures, breath work, and healing mantra, we will tune in for optimum balance and equanimity. Through this practice we will achieve emotional and personal empowerment.</p> <p>Short Bio: Mercedes is a Certified Yoga Instructor &amp; Intuitive Guide with a gift for bringing people together in celebration through yoga practices, aura attunements, Reiki healings, forgiveness ceremonies, and rituals for transforming Grief into Secondary Art. Mercedes is fluent in both English and Spanish and available for one-on-one sessions and group classes in either language. Mercedes attended yoga school after many years of practice to bring her passion for healing to others. She completed yoga training in the jungles of Costa Rica at Pavones Yoga Center. Fresh from yoga school, she traveled to Isla Ometepe, Nicaragua where she taught yoga. language, and wellness in local communities and resorts.<br/>",
//         "visibility": "public",
//       "member_pay_fee": false
//     },
//     {
//       "created": 1595615679000,
//       "duration": 5400000,
//       "fee": {
//         "accepts": "cash",
//         "amount": 25,
//         "currency": "USD",
//         "description": "",
//         "label": "Price",
//         "required": false
//       },
//       "id": "rkcxxrybcmbjc",
//       "name": "20 Secrets of Building Your Own Intuition",
//       "rsvp_limit": 15,
//       "date_in_series_pattern": false,
//       "status": "upcoming",
//       "time": 1601139600000,
//       "local_date": "2020-09-26",
//       "local_time": "10:00",
//       "updated": 1600720332000,
//       "utc_offset": -25200000,
//       "waitlist_count": 0,
//       "yes_rsvp_count": 2,
//       "venue": {
//         "id": 26916173,
//         "name": "HeartSpace Online",
//         "lat": 33.68795394897461,
//         "lon": -117.86682891845703,
//         "repinned": true,
//         "address_1": "18271 McDurmott W   ",
//         "address_2": "Suite G",
//         "city": "Irvine",
//         "country": "us",
//         "localized_country_name": "USA",
//         "zip": "92614",
//         "state": "ca"
//       },
//       "is_online_event": false,
//       "group": {
//         "created": 1279222664000,
//         "name": "Personal Growth Community - HeartSpace",
//         "id": 1676005,
//         "join_mode": "open",
//         "lat": 33.68000030517578,
//         "lon": -117.83000183105469,
//         "urlname": "smhasoc",
//         "who": "Seekers",
//         "localized_location": "Irvine, CA",
//         "state": "CA",
//         "country": "us",
//         "region": "en_US",
//         "timezone": "US/Pacific"
//       },
//       "link": "https://www.meetup.com/smhasoc/events/rkcxxrybcmbjc/",
//       "description": "<p>",
//         "how_to_find_us": "www.heartspaceoc.com",
//       "visibility": "public",
//       "member_pay_fee": false
//     },
//     {
//       "created": 1599628045000,
//       "duration": 7200000,
//       "fee": {
//         "accepts": "cash",
//         "amount": 25,
//         "currency": "USD",
//         "description": "",
//         "label": "Price",
//         "required": false
//       },
//       "id": "nmblxrybcmbmc",
//       "name": "Angel Card Intuitive Reading Certification Class",
//       "date_in_series_pattern": false,
//       "status": "upcoming",
//       "time": 1601431200000,
//       "local_date": "2020-09-29",
//       "local_time": "19:00",
//       "updated": 1600975783000,
//       "utc_offset": -25200000,
//       "waitlist_count": 0,
//       "yes_rsvp_count": 1,
//       "venue": {
//         "id": 1323803,
//         "name": "SMHAS - School of Multidimensional Healing Arts & Sciences",
//         "lat": 33.69095230102539,
//         "lon": -117.866943359375,
//         "repinned": true,
//         "address_1": "18271 McDurmott West, Suite H",
//         "city": "Irvine",
//         "country": "us",
//         "localized_country_name": "USA",
//         "phone": "949-752-5272",
//         "zip": "92614",
//         "state": "CA"
//       },
//       "is_online_event": false,
//       "group": {
//         "created": 1279222664000,
//         "name": "Personal Growth Community - HeartSpace",
//         "id": 1676005,
//         "join_mode": "open",
//         "lat": 33.68000030517578,
//         "lon": -117.83000183105469,
//         "urlname": "smhasoc",
//         "who": "Seekers",
//         "localized_location": "Irvine, CA",
//         "state": "CA",
//         "country": "us",
//         "region": "en_US",
//         "timezone": "US/Pacific"
//       },
//       "link": "https://www.meetup.com/smhasoc/events/nmblxrybcmbmc/",
//       "description": "<p>with Anne G angel</p> <p>Schedule Change! Tuesday instead of Wednesday</p> <p>7 – 9 pm Tuesdays</p> <p>Eight Week Certification Class. Start any Wednesday</p> <p>$25 each</p> <p>To Register and Pay:<br/>",
//         "visibility": "public",
//       "member_pay_fee": false
//     },
//     {
//       "created": 1599533515000,
//       "duration": 9000000,
//       "id": "273106923",
//       "name": "Sacred Healing Circle: Strong Confidence (ZOOM)",
//       "rsvp_limit": 20,
//       "date_in_series_pattern": false,
//       "status": "upcoming",
//       "time": 1601139600000,
//       "local_date": "2020-09-26",
//       "local_time": "10:00",
//       "updated": 1599533515000,
//       "utc_offset": -25200000,
//       "waitlist_count": 0,
//       "yes_rsvp_count": 7,
//       "venue": {
//         "id": 26906060,
//         "name": "Online event",
//         "repinned": false,
//         "country": "",
//         "localized_country_name": ""
//       },
//       "is_online_event": true,
//       "group": {
//         "created": 1249925706000,
//         "name": "Huntington Beach Reiki",
//         "id": 1504074,
//         "join_mode": "open",
//         "lat": 33.75,
//         "lon": -117.8499984741211,
//         "urlname": "Huntington-Beach-Reiki",
//         "who": "Healers",
//         "localized_location": "Santa Ana, CA",
//         "state": "CA",
//         "country": "us",
//         "region": "en_US",
//         "timezone": "US/Pacific"
//       },
//       "link": "https://www.meetup.com/Huntington-Beach-Reiki/events/273106923/",
//       "description": "<p>-Has low confidence affected your career and relationship?<br/>-Is lack of confidence stopping you from doing what you want?<br/>-Do you wish you have the confidence of the people you admire?</p> <p>​<br/>YOU ARE INVITED to join our Sacred Healing Circle, from anywhere you are on the planet. We will be working on having stronger confidence so we can do the things we want to and be the persons we want to be.</p> <p>REGISTER NOW to reserve your warm spot in the Circle.",
//         "how_to_find_us": "https://us02web.zoom.us/meeting/register/tZcod-qrrTsvHNIcmhl5MMy7Xe7ykONsL0jr",
//       "visibility": "public",
//       "member_pay_fee": false
//     },
//     {
//       "created": 1600705097000,
//       "duration": 7200000,
//       "fee": {
//         "accepts": "cash",
//         "amount": 30,
//         "currency": "USD",
//         "description": "",
//         "label": "Price",
//         "required": false
//       },
//       "id": "273411059",
//       "name": "Introduction to The Vibration of Love",
//       "date_in_series_pattern": false,
//       "status": "upcoming",
//       "time": 1602727200000,
//       "local_date": "2020-10-14",
//       "local_time": "19:00",
//       "updated": 1600705097000,
//       "utc_offset": -25200000,
//       "waitlist_count": 0,
//       "yes_rsvp_count": 2,
//       "venue": {
//         "id": 26906060,
//         "name": "Online event",
//         "repinned": false,
//         "country": "",
//         "localized_country_name": ""
//       },
//       "is_online_event": true,
//       "group": {
//         "created": 1279222664000,
//         "name": "Personal Growth Community - HeartSpace",
//         "id": 1676005,
//         "join_mode": "open",
//         "lat": 33.68000030517578,
//         "lon": -117.83000183105469,
//         "urlname": "smhasoc",
//         "who": "Seekers",
//         "localized_location": "Irvine, CA",
//         "state": "CA",
//         "country": "us",
//         "region": "en_US",
//         "timezone": "US/Pacific"
//       },
//       "link": "https://www.meetup.com/smhasoc/events/273411059/",
//       "description": "<p>Introduction to The Vibration of Love</p> <p>A Sound Healer’s Guide</p> <p>528 hz – the sound of love, transformation, healing</p> <p>Join us as we explore the vibration of sound. How it is measured, the pitches that are used to open the heart, the throat chakra, the pineal gland and more.</p> <p>How does sound affect our bodies, help us to heal and soothe us so that we may know moments of peace, quiet and a letting go in these chaotic times of great change? How does it affect our life force energy, the life force energies of this planet and how can we embrace the sounds with the greatest instrument of all – our voice?</p> <p>Wednesday, October 14, 2020 via Zoom</p> <p>7 to 9 pm P.S.T. $30</p>",
//         "visibility": "public",
//       "member_pay_fee": false
//     },
//     {
//       "created": 1591919561000,
//       "duration": 4500000,
//       "id": "ppfftrybcmbkc",
//       "name": "Yoga in the park with Matt",
//       "date_in_series_pattern": false,
//       "status": "upcoming",
//       "time": 1601226000000,
//       "local_date": "2020-09-27",
//       "local_time": "10:00",
//       "updated": 1591919561000,
//       "utc_offset": -25200000,
//       "waitlist_count": 0,
//       "yes_rsvp_count": 8,
//       "venue": {
//         "id": 26089217,
//         "name": "Mike Ward Community Park Woodbridge",
//         "lat": 33.67566680908203,
//         "lon": -117.80220031738281,
//         "repinned": true,
//         "address_1": "20 Lake Rd",
//         "city": "Irvine",
//         "country": "us",
//         "localized_country_name": "USA",
//         "zip": "92604",
//         "state": "CA"
//       },
//       "is_online_event": false,
//       "group": {
//         "created": 1591282459000,
//         "name": "Irvine Yoga In The Park",
//         "id": 33791395,
//         "join_mode": "open",
//         "lat": 33.7400016784668,
//         "lon": -117.75,
//         "urlname": "meetup-group-lOTlBtdi",
//         "who": "Members",
//         "localized_location": "Irvine, CA",
//         "state": "CA",
//         "country": "us",
//         "region": "en_US",
//         "timezone": "US/Pacific"
//       },
//       "link": "https://www.meetup.com/meetup-group-lOTlBtdi/events/ppfftrybcmbkc/",
//       "description": "<p>Meet us in Mike Ward Community Park for a strong flow to set the tone of your day. Matt's connection to yoga began over 10 years ago . He believes that yoga heals, transforms and provides balance in one's life. His mission is to draw out your best self. Whether it’s strength, balance, flexibility, peace, or clarity, Matt is an advocate for well roundedness. More importantly, have fun, smile and be joyful. Matt is a 500 hour certified yoga trainer and has led years of teacher training. He is also certified in Functional Range Conditioning (FRC), is a level one KINSTRETCH instructor, and is the owner operator of FLOW, Water Yoga Life in Huntington Beach.</p> <p>Bring a mat, water and maybe dress in layers for weather conditions. Class level 1-2 Vinyasa</p> <p>Donations are always appreciated<br/>Venmo @Matt-Patterson-13 (verification 7435)</p> <p>See you at the park!</p> ",
//       "how_to_find_us": "you can find yoga in the park on the grassy area between the senior center and the racquetball courts.  there's plenty of parking ",
//       "visibility": "public",
//       "member_pay_fee": false
//     },
//     {
//       "created": 1599695483000,
//       "duration": 5400000,
//       "fee": {
//         "accepts": "cash",
//         "amount": 25,
//         "currency": "USD",
//         "description": "",
//         "label": "Price",
//         "required": false
//       },
//       "id": "273148845",
//       "name": "Vedic Mantras Platform of Sound Healing",
//       "date_in_series_pattern": false,
//       "status": "upcoming",
//       "time": 1601337600000,
//       "local_date": "2020-09-28",
//       "local_time": "17:00",
//       "updated": 1599695483000,
//       "utc_offset": -25200000,
//       "waitlist_count": 0,
//       "yes_rsvp_count": 3,
//       "venue": {
//         "id": 26906060,
//         "name": "Online event",
//         "repinned": false,
//         "country": "",
//         "localized_country_name": ""
//       },
//       "is_online_event": true,
//       "group": {
//         "created": 1279222664000,
//         "name": "Personal Growth Community - HeartSpace",
//         "id": 1676005,
//         "join_mode": "open",
//         "lat": 33.68000030517578,
//         "lon": -117.83000183105469,
//         "urlname": "smhasoc",
//         "who": "Seekers",
//         "localized_location": "Irvine, CA",
//         "state": "CA",
//         "country": "us",
//         "region": "en_US",
//         "timezone": "US/Pacific"
//       },
//       "link": "https://www.meetup.com/smhasoc/events/273148845/",
//       "description": "<p>Sound is deeply connected to consciousness, shift bio field, instant realignment tool, and deep uniting w divine universe. Voice carries and can carry all the elements. Mantras are a kind of healing vibration for our minds. They are a powerful means of focusing the mind while filling our consciousness with positive vibrations.</p> <p>We will cover the following in this class:<br/>-How the mantras simple chanting can help Sleep better, reduce anxiety-depression-stress,<br/>-Cope with health issues, relationships, emotional issues to deal with today’s challenging times.<br/>-Information on different Mantras and their connection with divine, color, planets, chakras.<br/>-Special mantras for chakras.<br/>-Meditation wit canting different mantras.</p> <p>Monday September 28<br/>5-6:30 pm<br/>Cost-$25</p>",
//         "visibility": "public",
//       "member_pay_fee": false
//     },
//     {
//       "created": 1599766245000,
//       "duration": 7200000,
//       "fee": {
//         "accepts": "cash",
//         "amount": 25,
//         "currency": "USD",
//         "description": "",
//         "label": "Price",
//         "required": false
//       },
//       "id": "zjjmxrybcnbjb",
//       "name": "Manifesting From Your Soul Code",
//       "date_in_series_pattern": false,
//       "status": "upcoming",
//       "time": 1602036000000,
//       "local_date": "2020-10-06",
//       "local_time": "19:00",
//       "updated": 1600706257000,
//       "utc_offset": -25200000,
//       "waitlist_count": 0,
//       "yes_rsvp_count": 2,
//       "venue": {
//         "id": 26906060,
//         "name": "Online event",
//         "repinned": false,
//         "country": "",
//         "localized_country_name": ""
//       },
//       "is_online_event": true,
//       "group": {
//         "created": 1279222664000,
//         "name": "Personal Growth Community - HeartSpace",
//         "id": 1676005,
//         "join_mode": "open",
//         "lat": 33.68000030517578,
//         "lon": -117.83000183105469,
//         "urlname": "smhasoc",
//         "who": "Seekers",
//         "localized_location": "Irvine, CA",
//         "state": "CA",
//         "country": "us",
//         "region": "en_US",
//         "timezone": "US/Pacific"
//       },
//       "link": "https://www.meetup.com/smhasoc/events/zjjmxrybcnbjb/",
//       "description": "<p>with Roz Esposito</p> <p>As you unplug from your daily routines, there is an opening and an opportunity to recognize what’s truly meaningful in your life. What no longer fits? What wants to emerge? Join us for a deep dive into accessing your Soul Code – that which is indelibly etched upon your soul – your true calling in this life. From this place you unleash the tremendous power to manifest without resistance.</p> <p>7 PM – 9 PM<br/>Cost: $25</p> <p>RSVP at: <a href="https://heartspaceoc.com/event/manifesting-from-your-soul-code-9-03-2020-09-10-2020-09-15/" class="linkified">https://heartspaceoc.com/event/manifesting-from-your-soul-code-9-03-2020-09-10-2020-09-15/</a></p> <p>Rev Roz Esposito – Intuitive Guide<br/>I specialize in getting to the core of what’s holding you back, clearing old mental patterns and instigating change that moves you forward in whatever area you feel stuck. I work on both immediate concerns such as making important decisions, resolving conflicts, as well as long term goals such as discovering your life’s purpose or soul code. I’ve studied with Sufi Masters, Eastern Mystics, worked privately with Louise Hay and Michael Bernard Beckwith, combining these teachings into my own brand of self-development. I’d love to help you move forward.</p> ",
//         "visibility": "public",
//       "member_pay_fee": false
//     },
//     {
//       "created": 1595099259000,
//       "duration": 5400000,
//       "id": "gblmvrybcmbkc",
//       "name": "AAGAPE SOUTH On-Line - Guided Meditation – Life Structure Talk – Community & You",
//       "date_in_series_pattern": false,
//       "status": "upcoming",
//       "time": 1601227800000,
//       "local_date": "2020-09-27",
//       "local_time": "10:30",
//       "updated": 1595099259000,
//       "utc_offset": -25200000,
//       "waitlist_count": 0,
//       "yes_rsvp_count": 1,
//       "venue": {
//         "id": 26906060,
//         "name": "Online event",
//         "repinned": false,
//         "country": "",
//         "localized_country_name": ""
//       },
//       "is_online_event": true,
//       "group": {
//         "created": 1279222664000,
//         "name": "Personal Growth Community - HeartSpace",
//         "id": 1676005,
//         "join_mode": "open",
//         "lat": 33.68000030517578,
//         "lon": -117.83000183105469,
//         "urlname": "smhasoc",
//         "who": "Seekers",
//         "localized_location": "Irvine, CA",
//         "state": "CA",
//         "country": "us",
//         "region": "en_US",
//         "timezone": "US/Pacific"
//       },
//       "link": "https://www.meetup.com/smhasoc/events/gblmvrybcmbkc/",
//       "description": "<p>AGAPE SOUTH on Sunday’s - ZOOM On-Line Meditation and Service.<br/>Join Rev. Susan Shahani trained by Reverend Dr. Michael Bernard Beckwith, at the Agape International Spiritual Center in LA.</p> <p>FEELING SPIRITUAL BUT NOT RELIGIOUS<br/>Do you believe that your thoughts and internal self-talk, have anything to do with the life you are now experiencing and reality you have created?</p> <p>“Everything is energy. Match the frequency of the reality you want, and you cannot help but get that reality. It can be no other way. This is not philosophy. This is physics.”</p> <p>Community Builds Immunity! Be safe – Be Well as we Navigate this time together with direction and purpose.<br/>10:30 Meditation<br/>11:00 Inspirational Talk<br/>Let’s maintain a sense of Peace &amp; Calm, Possibilities &amp; Love</p> <p>How have you changed since being at home?<br/>What are your new priorities, values?<br/>What are you choosing?<br/>Who are you becoming?</p> <p>10:30 Meditation<br/>11:00 Inspirational Talk</p> <p>Do you have Zoom?",
//         "how_to_find_us": "https://zoom.us/j/226971396",
//       "visibility": "public",
//       "member_pay_fee": false
//     },
//     {
//       "created": 1599766245000,
//       "duration": 7200000,
//       "fee": {
//         "accepts": "cash",
//         "amount": 25,
//         "currency": "USD",
//         "description": "",
//         "label": "Price",
//         "required": false
//       },
//       "id": "zjjmxrybcmbmc",
//       "name": "Manifesting From Your Soul Code",
//       "date_in_series_pattern": false,
//       "status": "upcoming",
//       "time": 1601431200000,
//       "local_date": "2020-09-29",
//       "local_time": "19:00",
//       "updated": 1600975906000,
//       "utc_offset": -25200000,
//       "waitlist_count": 0,
//       "yes_rsvp_count": 3,
//       "venue": {
//         "id": 26906060,
//         "name": "Online event",
//         "repinned": false,
//         "country": "",
//         "localized_country_name": ""
//       },
//       "is_online_event": true,
//       "group": {
//         "created": 1279222664000,
//         "name": "Personal Growth Community - HeartSpace",
//         "id": 1676005,
//         "join_mode": "open",
//         "lat": 33.68000030517578,
//         "lon": -117.83000183105469,
//         "urlname": "smhasoc",
//         "who": "Seekers",
//         "localized_location": "Irvine, CA",
//         "state": "CA",
//         "country": "us",
//         "region": "en_US",
//         "timezone": "US/Pacific"
//       },
//       "link": "https://www.meetup.com/smhasoc/events/zjjmxrybcmbmc/",
//       "description": "<p>with Roz Esposito</p> <p>As you unplug from your daily routines, there is an opening and an opportunity to recognize what’s truly meaningful in your life. What no longer fits? What wants to emerge? Join us for a deep dive into accessing your Soul Code – that which is indelibly etched upon your soul – your true calling in this life. From this place you unleash the tremendous power to manifest without resistance.</p> <p>7 PM – 9 PM<br/>Cost: $25</p> <p>RSVP at: <a href="https://heartspaceoc.com/event/manifesting-from-your-soul-code-9-03-2020-09-10-2020-09-29/" class="linkified">https://heartspaceoc.com/event/manifesting-from-your-soul-code-9-03-2020-09-10-2020-09-29/</a></p> <p>Rev Roz Esposito – Intuitive Guide<br/>I specialize in getting to the core of what’s holding you back, clearing old mental patterns and instigating change that moves you forward in whatever area you feel stuck. I work on both immediate concerns such as making important decisions, resolving conflicts, as well as long term goals such as discovering your life’s purpose or soul code. I’ve studied with Sufi Masters, Eastern Mystics, worked privately with Louise Hay and Michael Bernard Beckwith, combining these teachings into my own brand of self-development. I’d love to help you move forward.</p> ",
//         "visibility": "public",
//       "member_pay_fee": false
//     },
//     {
//       "local_time": "09:30",
//       "local_date": "2020-09-27",
//       "link": "https://www.meetup.com/Meditative-Hiking-and-Spiritual-Growth/events/273354345/",
//       "visibility": "public_limited",
//       "group": {
//         "created": 1570154814000,
//         "name": "Meditative Hiking and Spiritual Growth",
//         "id": 32846021,
//         "join_mode": "approval",
//         "lat": 33.779998779296875,
//         "lon": -117.83999633789062,
//         "urlname": "Meditative-Hiking-and-Spiritual-Growth",
//         "who": "Meditative Hikers",
//         "localized_location": "Orange, CA",
//         "state": "CA",
//         "country": "us",
//         "region": "en_US",
//         "timezone": "US/Pacific"
//       },
//       "waitlist_count": 0,
//       "yes_rsvp_count": 10,
//       "duration": 10800000,
//       "time": 1601224200000,
//       "utc_offset": -25200000,
//       "name": "Meditation  & Sound Bath & Reiki on A TREE",
//       "id": "273354345"
//     },
//     {
//       "created": 1600545770000,
//       "duration": 3600000,
//       "id": "273373660",
//       "name": "Yoga For Success (Free Online Webinar) Open to All",
//       "date_in_series_pattern": false,
//       "status": "upcoming",
//       "time": 1601341200000,
//       "local_date": "2020-09-28",
//       "local_time": "18:00",
//       "updated": 1600545770000,
//       "utc_offset": -25200000,
//       "waitlist_count": 0,
//       "yes_rsvp_count": 6,
//       "venue": {
//         "id": 26906060,
//         "name": "Online event",
//         "repinned": false,
//         "country": "",
//         "localized_country_name": ""
//       },
//       "is_online_event": true,
//       "group": {
//         "created": 1459273797000,
//         "name": "Inner Engineering OC (Isha Yoga & Meditation Classes)",
//         "id": 19773615,
//         "join_mode": "open",
//         "lat": 33.7400016784668,
//         "lon": -117.75,
//         "urlname": "Inner-Engineering-OC-Isha-Yoga-Meditation-Classes",
//         "who": "Meditators",
//         "localized_location": "Irvine, CA",
//         "state": "CA",
//         "country": "us",
//         "region": "en_US",
//         "timezone": "US/Pacific"
//       },
//       "link": "https://www.meetup.com/Inner-Engineering-OC-Isha-Yoga-Meditation-Classes/events/273373660/",
//       "description": "<p>Please click here to RSVP. Once you click on this link, please provide your email address and you will receive an email with details on how you can join the webinar.<br/><a href="https://www.innerengineering.com/webinar/yoga-for-success" class="linkified">https://www.innerengineering.com/webinar/yoga-for-success</a></p> <p>How successful you are in life simply depends on how well you can use your mind and body. This session offers simple, but powerful yoga postures to bring stability and balance.<br/>- Can improve memory, concentration, and mental clarity<br/>- Can relieve stress and anxiety<br/>- Strengthens the spine<br/>- Takes only 5-10 minutes to practice daily</p> <p>Designed by Sadhguru, a self- realized yogi and foremost authority in the field of yoga.</p> <p>This session will be conducted by a trained Isha facilitator, after which ongoing online support will also be available.</p> <p>Age 7 &amp; up</p> <p>This session is brought to you by Isha foundation, an international non-profit aimed to bring well-being to everyone through yoga and meditation.</p> ",
//         "visibility": "public",
//       "pro_is_email_shared": false,
//       "member_pay_fee": false
//     },
//     {
//       "created": 1601046867000,
//       "duration": 3600000,
//       "id": "273505079",
//       "name": "How to Manage Stress and Have Happier Relationships",
//       "date_in_series_pattern": false,
//       "status": "upcoming",
//       "time": 1601431200000,
//       "local_date": "2020-09-29",
//       "local_time": "19:00",
//       "updated": 1601046867000,
//       "utc_offset": -25200000,
//       "waitlist_count": 0,
//       "yes_rsvp_count": 2,
//       "venue": {
//         "id": 26906060,
//         "name": "Online event",
//         "repinned": false,
//         "country": "",
//         "localized_country_name": ""
//       },
//       "is_online_event": true,
//       "group": {
//         "created": 1596924001000,
//         "name": "How to Have Healthy, Non-Toxic Relationships",
//         "id": 34070696,
//         "join_mode": "open",
//         "lat": 33.650001525878906,
//         "lon": -117.66999816894531,
//         "urlname": "How-to-Have-Healthy-Non-Toxic-Relationships",
//         "who": "Members",
//         "localized_location": "Lake Forest, CA",
//         "state": "CA",
//         "country": "us",
//         "region": "en_US",
//         "timezone": "US/Pacific"
//       },
//       "link": "https://www.meetup.com/How-to-Have-Healthy-Non-Toxic-Relationships/events/273505079/",
//       "description": "<p>We’d like to invite Meetup members to a free webinar on overcoming stress and anxiety.</p> <p>Stress and anxiety can come about as a result of environmental or internal pressures. These internal pressures are from past stressful experiences that continue to impinge on you in the present.</p> <p>Typical circumstances that cause stress or anxiety include:</p> <p>• Issues at work, or lack of work<br/>• Problems in the home<br/>• An unhappy relationship<br/>• Poor health, difficulty losing weight<br/>• A painful breakup or divorce<br/>• Illness or death of a loved one, friend or pet<br/>• A shock of some kind</p> <p>There are various remedies offered for anxiety and stress, however most of them don’t have lasting effects. Solutions such as medications, drugs and alcohol have side effects and can worsen the issue over the long term.</p> <p>In this webinar we will discuss how you can permanently reduce stress and anxiety in your life. You’ll learn the reasons stress or anxiety persist despite the lapse of time or efforts to control them.</p> <p>Feelings of anxiety can remain even when you’ve removed yourself from its immediate source, such as breaking up, changing jobs or moving away, and you’ll learn why that is.</p> <p>We’ll also show you how you can be stronger and more confident so that stressful situations have less or even no immediate or lasting effect on you.</p> <p>PLEASE MESSAGE US IF YOU HAVE ANY QUESTIONS ON HOW TO ACCESS THE WEBINAR OR ABOUT THE WEBINAR.</p> <p>This webinar is hosted by Diana Dernehl, Self-Help Expert, Executive Director Dianetics &amp; Scientology Life Improvement Center.</p> ",
//       "visibility": "public",
//       "member_pay_fee": false
//     },
//     {
//       "local_time": "19:30",
//       "local_date": "2020-09-29",
//       "link": "https://www.meetup.com/OCAP714/events/kpcfkrybcmbmc/",
//       "visibility": "public_limited",
//       "group": {
//         "created": 1226038210000,
//         "name": "Orange County Asian Professionals OCAP",
//         "id": 1316229,
//         "join_mode": "approval",
//         "lat": 33.70000076293945,
//         "lon": -117.76000213623047,
//         "urlname": "OCAP714",
//         "who": "OCAP Peeps",
//         "localized_location": "Irvine, CA",
//         "state": "CA",
//         "country": "us",
//         "region": "en_US",
//         "timezone": "US/Pacific"
//       },
//       "waitlist_count": 0,
//       "yes_rsvp_count": 7,
//       "duration": 9000000,
//       "time": 1601433000000,
//       "utc_offset": -25200000,
//       "name": "Co-Ed Flag-Football Tuesdays! (Not soccer)",
//       "id": "kpcfkrybcmbmc"
//     },
//     {
//       "local_time": "19:30",
//       "local_date": "2020-10-06",
//       "link": "https://www.meetup.com/OCAP714/events/kpcfkrybcnbjb/",
//       "visibility": "public_limited",
//       "group": {
//         "created": 1226038210000,
//         "name": "Orange County Asian Professionals OCAP",
//         "id": 1316229,
//         "join_mode": "approval",
//         "lat": 33.70000076293945,
//         "lon": -117.76000213623047,
//         "urlname": "OCAP714",
//         "who": "OCAP Peeps",
//         "localized_location": "Irvine, CA",
//         "state": "CA",
//         "country": "us",
//         "region": "en_US",
//         "timezone": "US/Pacific"
//       },
//       "waitlist_count": 0,
//       "yes_rsvp_count": 4,
//       "duration": 9000000,
//       "time": 1602037800000,
//       "utc_offset": -25200000,
//       "name": "Co-Ed Flag-Football Tuesdays! (Not soccer)",
//       "id": "kpcfkrybcnbjb"
//     },
//     {
//       "local_time": "19:30",
//       "local_date": "2020-10-13",
//       "link": "https://www.meetup.com/OCAP714/events/kpcfkrybcnbrb/",
//       "visibility": "public_limited",
//       "group": {
//         "created": 1226038210000,
//         "name": "Orange County Asian Professionals OCAP",
//         "id": 1316229,
//         "join_mode": "approval",
//         "lat": 33.70000076293945,
//         "lon": -117.76000213623047,
//         "urlname": "OCAP714",
//         "who": "OCAP Peeps",
//         "localized_location": "Irvine, CA",
//         "state": "CA",
//         "country": "us",
//         "region": "en_US",
//         "timezone": "US/Pacific"
//       },
//       "waitlist_count": 0,
//       "yes_rsvp_count": 4,
//       "duration": 9000000,
//       "time": 1602642600000,
//       "utc_offset": -25200000,
//       "name": "Co-Ed Flag-Football Tuesdays! (Not soccer)",
//       "id": "kpcfkrybcnbrb"
//     },
//     {
//       "local_time": "19:30",
//       "local_date": "2020-10-20",
//       "link": "https://www.meetup.com/OCAP714/events/kpcfkrybcnbbc/",
//       "visibility": "public_limited",
//       "group": {
//         "created": 1226038210000,
//         "name": "Orange County Asian Professionals OCAP",
//         "id": 1316229,
//         "join_mode": "approval",
//         "lat": 33.70000076293945,
//         "lon": -117.76000213623047,
//         "urlname": "OCAP714",
//         "who": "OCAP Peeps",
//         "localized_location": "Irvine, CA",
//         "state": "CA",
//         "country": "us",
//         "region": "en_US",
//         "timezone": "US/Pacific"
//       },
//       "waitlist_count": 0,
//       "yes_rsvp_count": 4,
//       "duration": 9000000,
//       "time": 1603247400000,
//       "utc_offset": -25200000,
//       "name": "Co-Ed Flag-Football Tuesdays! (Not soccer)",
//       "id": "kpcfkrybcnbbc"
//     }
//   ]
